function [BW_out,properties] = filterRegions_area(BW_out, min_area)
%filterRegions  Filter BW image using auto-generated code from imageRegionAnalyzer app.
%  [BW_OUT,PROPERTIES] = filterRegions(BW_IN) filters binary image BW_IN
%  using auto-generated code from the imageRegionAnalyzer app. BW_OUT has
%  had all of the options and filtering selections that were specified in
%  imageRegionAnalyzer applied to it. The PROPERTIES structure contains the
%  attributes of BW_out that were visible in the app.

% Auto-generated by imageRegionAnalyzer app on 09-Jul-2018
%---------------------------------------------------------

% Filter image based on image properties.


% min_MAL = 20;
% BW_out = bwpropfilt(BW_out, 'MajorAxisLength', [min_MAL + eps(min_MAL), Inf]);

% Get properties.
properties = regionprops(BW_out, {'Area', 'Eccentricity', 'EquivDiameter', 'EulerNumber', 'MajorAxisLength', 'MinorAxisLength', 'Orientation', 'Perimeter'});

% Sort the properties.
properties = sortProperties(properties, 'Area');

% Uncomment the following line to return the properties in a table.
% properties = struct2table(properties);



function properties = sortProperties(properties, sortField)

% Compute the sort order of the structure based on the sort field.
[~,idx] = sort([properties.(sortField)], 'descend');

% Reorder the entire structure.
properties = properties(idx);
